### ISSUE TITLE
兄弟，你真的去了深圳了？我在V2EX看到的

### ISSUE THREAD

**Issue by lijiaxu1996** [Cherrymelon/CV#1]
今年我二战北邮计算机，成绩还没出来，英语一感觉完蛋了。调剂只能双非了，感觉不值（主要年纪大了）
想先找工作。
大学期间好好学过web前端，我是16-20，但是年纪也不小了，96的（无工作经验，但是我这几天好好在准备我的一些作品集啥的）。
现在想想校招是不可能了，只能社招了。
现在看到你的简历感觉自己写简历有方向了。
谢谢你啦。

**Comment by Cherrymelon** [comment]
应届社招会比校招难不少,不足在于项目经验,多准备准备基础吧,如果公司有对你有意向,不会太多为难你项目经验,基础会考察的多一点,特别是还看你考过研

**Comment by lijiaxu1996** [comment]
好的，谢啦

Rui <notifications@github.com> 于2021年1月22日周五 上午10:31写道：
